### ISSUE TITLE
Workflow controller microservice

### ISSUE THREAD

**Issue by chdinh** [brain-link/scanhub#4]
Implementation of a workflow manager/controller which processes a predefined list of workflows.
Each workflow might trigger other workflows and thereby extend the list of process steps (see diagram below).

**ToDo's**

- [ ] Extension of communication object by list of workflows
- [ ] Definition of workflow job in library (scanhub-tools)
- [ ] Implementation of a few examples
- [ ] List registered workflows
- [ ] Documentation on how to create a new workflow

![Unbenannte Zeichnung(1)](https://github.com/brain-link/scanhub/assets/42237900/c9bc36a8-a22d-4252-b174-cd9966f11c69)

**Comment by schote** [comment]
Still up to date?
