### ISSUE TITLE
Refactoring of Jobs/Workflows

### ISSUE THREAD

**Issue by chdinh** [brain-link/scanhub#90]
With the input from the A4IM Hackathon in Freiburg the Job was refactored.
A job now contains a list of tasks. A task can either describe a data acquisition step (device-task) or a processing step (processing-step). The job database model has been modified accordingly and a new table for tasks has been implemented:

```
class Task(Base):
    """Task ORM model."""

    __tablename__ = "task"
    __table_args__ = {"extend_existing": True}

    # Use uuid here
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    description: Mapped[str] = mapped_column(nullable=False)
    type: Mapped[TaskType] = mapped_column(type_=JSON, nullable=False)

    # Arguments and parameters
    # Example: "args": {"arg1": "x", "arg2": "y"}
    args: Mapped[dict[str, str]] = mapped_column(type_=JSON, nullable=True)
    # acquisition_limits: Mapped[AcquisitionLimits] = mapped_column(type_=JSON, nullable=False)
    # sequence_parameters: Mapped[SequenceParameters] = mapped_column(type_=JSON, nullable=False)
    # device_parameters: Mapped[DeviceParameters] = mapped_column(type_=JSON, nullable=False)


    # Input and output artifacts with export destination
    # Example: {"input": [{"name": "env_HOLOSCAN_INPUT_PATH", "value": "{{ context.input.dicom }}"}]}
    # https://github.com/Project-MONAI/monai-deploy/blob/main/deploy/monai-deploy-express/sample-workflows/hello-world.json
    artifacts: Mapped[dict[str, list[dict[str, str]]]] = mapped_column(type_=JSON, nullable=True) # implemention of input and output artifacts for artifact types as replacement for string

    # List of task destinations, which are for example used to create the chain of topics in the kafka message broker, i.e., target topics
    task_destinations: Mapped[list[dict[str, str]]] = mapped_column(type_=JSON, nullable=True)

    # Relations and references
    job_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("job.id"))

    status: Mapped[dict[TaskStatus, str]] = mapped_column(type_=JSON, nullable=False)

    # Fields
    datetime_created: Mapped[datetime.datetime] = mapped_column(
        server_default=func.now()  # pylint: disable=not-callable
    )
```
 
### ToDo's

- [x] Task database table
- [x] Task pydantic model
- [x] Task data acess layer
- [x] Task endpoints
- [x] Update Job
- [x] Remove obsolete models
- [x] Consequently use models defined in shared_lib instead of exam-manager models

### Notes

- Output/input artifacts are in stored in a shared datalake, parent folder corresponds to job-id, subfolder can be defined in artifact
- Inputs and outputs are described by artifacts, i.e. they contain the file paths
- Arguments are specific for devices/acquisitions, it might be hard to fully describe them in advance (by using a pedantic model). For now it has been decided to pass any parameters as a dictionary contained in `args`
- Some of the job parameters has been moved to the patient database (weight, height, gender). When performing an acquisition, only the parameters relevant for the SAR calculation should be obtainable, i.e. patient data must not be accessible by the workflow-manager and acquisition-control. Could be solved by patient endpoint for SAR endpoint
